stages:
  - build
  - deploy-gcp

build_images:
  stage: build
  image: docker:20.10.16

  services:
    - docker:20.10.16-dind
  
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $USUARIO -p $SENHA

  script:
    - docker build -t lumr/desafio-dio-backend:1.0 backend/.
    - docker build -t lumr/desafio-dio-database:1.0 database/.
    - docker push lumr/desafio-dio-backend:1.0
    - docker push lumr/desafio-dio-database:1.0

deploy_gcp:
    
  stage: deploy-gcp

  before_script:
    - chmod 400 $SSH_KEY

   # script para realizar um acesso remoto a VM na GCP baixar os códigos necessários do github e utilizar os comandos necessários para criar o serviço e criar o deployment da imagem
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY gcp@$SSH_SERVER "sudo rm -Rf ./desafio-dio-kubernetes-cicd/ && sudo git clone https://gitlab.com/lumr92/app-cicd-dio.git && cd app-cicd-dio && sudo chmod +x ./script.sh && ./script.sh"
